<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PRAJWAL-PC" name="com.jbk.tests.OperatorsPageTest" tests="9" failures="1" timestamp="15 Jul 2021 09:44:46 GMT" time="6.029" errors="0">
  <testcase name="verifypersonWithWhatsappOnly" time="0.995" classname="com.jbk.tests.OperatorsPageTest"/>
  <testcase name="verifyPersonWithContactAndTime" time="1.397" classname="com.jbk.tests.OperatorsPageTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.jbk.tests.OperatorsPageTest.verifyPersonWithContactAndTime(OperatorsPageTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verifyPersonWithContactAndTime -->
  <testcase name="verifyContainsString" time="0.672" classname="com.jbk.tests.OperatorsPageTest"/>
  <testcase name="verifytableId" time="0.590" classname="com.jbk.tests.OperatorsPageTest"/>
  <testcase name="verifyHeaderOfTable" time="0.360" classname="com.jbk.tests.OperatorsPageTest"/>
  <testcase name="verifyPersonEnquiry" time="1.015" classname="com.jbk.tests.OperatorsPageTest"/>
  <testcase name="verifyAllDayAvailablePerson" time="0.937" classname="com.jbk.tests.OperatorsPageTest"/>
  <testcase name="verifyIsPersonNameIsSorted" time="0.063" classname="com.jbk.tests.OperatorsPageTest"/>
  <testcase name="verifyTitle" time="0.000" classname="com.jbk.tests.OperatorsPageTest"/>
</testsuite> <!-- com.jbk.tests.OperatorsPageTest -->
